http:
  port: "8081"
  
american:
  host: "american-api-jag.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id:  "3446ad8228fc491f8959a3d129bd18de"
  client_secret:  "d93dC0486D054a8e87F5964e4c84A05f"
  
training:
  host: "ilt.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://ilt.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"