#%RAML 1.0 NamedExample

value:

  -

    ID: 1
    Name: ramesh
    Acc_Type: Personal
    Address: "2nd street,california,usa"
    Air_miles:  2344
    creation_date:  2016-05-28T12:41:41.090Z
  -

    ID: 2
    Name: Suresh
    Acc_Type: Business
    Address: "3rd street,california,usa"
    Air_miles: 6788
    creation_date:  2016-03-28T15:41:41.090Z
  -

    ID: 3
    Name: Ram
    Acc_Type: Business
    Address:  "4th street,california,usa"
    Air_miles:  9877
    creation_date:  2016-02-28T16:41:41.090Z



